on:
  workflow_dispatch:

jobs:
  # This job finds all repositories that have files to update and groups the files.
  find-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Find all md and ipynb files
        id: set-matrix
        env:
          # Use your Personal Access Token with repo and workflow scopes
          GH_TOKEN: ${{ secrets.CROSS_REPO_PAT }}
        run: |
          echo "Finding repositories..."
          REPOS=$(gh repo list --limit 1000 --json nameWithOwner | jq -r '.[].nameWithOwner')
          
          echo "Building matrix of repositories and their files..."
          MATRIX="{\"include\":["
          FIRST_REPO=true
          
          for REPO in $REPOS; do
            # Find all .md and .ipynb files and convert the list to a single space-separated string
            FILES=$(gh api "repos/$REPO/git/trees/main?recursive=1" -q '.tree[].path | select(endswith(".md") or endswith(".ipynb"))' | tr '\n' ' ' | sed 's/ $//')
            
            # Only add the repo to the matrix if it has files to update
            if [ -n "$FILES" ]; then
              if [ "$FIRST_REPO" = false ]; then
                MATRIX="$MATRIX,"
              fi
              # Add the repo and the string of file paths to our matrix
              MATRIX="$MATRIX{\"repo\":\"$REPO\", \"files\":\"$FILES\"}"
              FIRST_REPO=false
            fi
          done
          
          MATRIX="$MATRIX]}"
          echo "Matrix generation complete."
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  # This job calls the reusable workflow ONCE PER REPOSITORY
  update-badges:
    needs: find-files
    # Only run this job if repositories with files were actually found
    if: needs.find-files.outputs.matrix != '{"include":[]}'
    strategy:
      # Use the matrix of repositories generated by the previous job
      matrix: ${{ fromJson(needs.find-files.outputs.matrix) }}
      fail-fast: false # Don't cancel all jobs if one fails

    # This calls your central, reusable workflow
    uses: ./.github/workflows/update_badges.yml
    with:
      repo_name: ${{ matrix.repo }}
      file_paths: ${{ matrix.files }} # Pass the whole string of files
    # Pass the PAT secret to the reusable workflow
    secrets:
      cross_repo_pat: ${{ secrets.CROSS_REPO_PAT }}
